### ISSUE TITLE
It's always crashing

### ISSUE THREAD

**Issue by Shazgul** [freshSauce/UniversalProxyScraper#1]
```
Traceback (most recent call last):
  File "C:\Proxys\UniversalProxyScraper-master\main.py", line 358, in <module>
    result = ProxyScraper(args['file'], args['output'], args['verify']).Proxies(args['quantity'])
  File "C:\Proxys\UniversalProxyScraper-master\main.py", line 320, in Proxies
    proxy_list = self.__scrape(html['html'], html['site'])
  File "C:\Proxys\UniversalProxyScraper-master\main.py", line 190, in __scrape
    table_body = re.search(pattern, html.strip()).group()
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by freshSauce** [comment]
Sorry for the wait, seems like spys.one have been changing their website code lately, right now the scraper seems to be working fine, also, I recommend to scrape the spys.one/en URL :)
